pytransitions/transitions

transitions/core.py
adding the flag causes the states to ignore triggers that are not defined.
=> NEW added optional 'ignore' flag to States

tests/test_transitions.py, transitions/core.py
The callbacks are called every time a transition happens and have the same call signature as normal callbacks
This patch address #13
=> Add support for generic callbacks in the Machine

README.md
The tutorial contained a small bug in that the say_goodbye callback was (in the text) associated to State_a, but later executed when the sublimate trigger was called on the state `solid'. I replaced the names State_a and so on into the states solid and so on to line up this example of callback with the rest of the tutorial
=> Replaced State_a and so on into solid and so on

.gitignore, tests/test_transitions.py, transitions/core.py
Hey,
I've recently found that it would be useful if condition functions also had access to EventData (or args/kwargs) so that data can be passed through when triggering a transition to help determine whether the transition should succeed or not.
Here's a PR implementing this feature. Would appreciate it if you could take a look, thanks!
=> make send_event also pass EventData through to conditions

transitions/core.py
This adds more verbosity when an invalid transition is executed when `ignore_invalid_triggers` is `True`.
=> Log a warning for an invalid trigger if ignore_invalid_triggers is True

.travis.yml, requirements_test.txt, setup.py, tests/test_diagrams.py, transitions/core.py, transitions/diagrams.py
I've split up the graphs, so we can perhaps add different diagram types later on, not sure if we want that right now, but it's easier to scale out later on. The `Machine.get_graph()` method will return a pygraphviz object.
You can render a png like this:
```
In [7]: machine.get_graph().draw('foobar.png', prog='dot')
```
Or you can render the dot markup directly to string:
```
In [8]: print machine.get_graph()
digraph {
graph [rankdir=LR,
ratio=0.3,
title=AGraph
];
node [height=1.2,
label="\N",
shape=circle
];
...
}
```
I defaulted to the AGraph diagram type, you can override or provide your own diagram classes by subclassing Diagram or in this case AGraph, eg for creating square images:
```
from transitions.diagrams import AGraph
class BlockAGraph(AGraph):
state_attributes = {
'shape': …
```
=> Create diagram from machine states and triggers

README.md, tests/test_threading.py, transitions/diagrams.py, transitions/extensions.py
Hi,
I fixed LockedHSM to use LockedNestedTranstions and fixed pickling issues for python 2.7.  I added a pickling test to test_threading. However, pickle does not support thread locks which means it fails now for python > 3 but dill does…
I also ‘fixed’ the double circle thing but could revert changes in `AGraph` and `AAGraph` since @wtgee is also working on it.
=> Locked(HSM) Fixes & Diagram Doublecircle

tests/test_threading.py, transitions/extensions.py
To be pickled
* objects should not be local
-> moved locked_method to callable object LockedMethod
* subclasses should not mess around with __getattribute__
-> Even though the method was found with __getattribute__, __getattr__
was called in pickle.load(). I assume this has something to do with the
order in which objects are deserialized. Overriding __getattr__ of the
subclass with __getattribute__ of the base class solves the issue.
I also expanded the pickle test in test_threading to check if locking still works after pickling.
=> Fix for #59

tests/test_graphing.py, tests/test_nesting.py, tests/test_reuse.py, tests/test_threading.py, transitions/diagrams.py, transitions/extensions.py
To reduce redundancy I let test_nesting and test_threading inherit from `TestTransitions` in test_core. This way I stumbled upon a bug in `LockedMachine.__getattr__`. I assumed `__getattribute__` will call `__getattr__` implicitely if it fails to find the item. But that does not seem to be the case. LockedMachine causes an `AttributeError` for         Machine.on_enter_State
Calling `super.__getattr__` as a fallback solves this issue.
=> Improved Testing & __getattr__ LockedMachine fix

.travis.yml, README.md
While poking around with #40 I made a few tweaks to the readme for consistency, and changed the travis config because 3-minute-long builds are an awful thing. I've split these out separately from my other branches as they're probably useful.
The new container infrastructure is much faster - there are a few caveats (can't use sudo is the major one) but none that would affect transitions that I can see.
The docs are below; please check them before merging in case I've missed anything. Travis-CI are happy enough with the new infrastructure that it has been the default for new repositories for a year.
This link: https://docs.travis-ci.com/user/workers/standard-infrastructure indicates the change can be backed out by reverting the .yml and adding `sudo: required`. …
=> Modify travis config to use container builds

README.md, tests/test_core.py, transitions/core.py, transitions/extensions/nesting.py
There seemed to be something of a consensus forming in #40, so I've continued with the changes I've already made by renaming the 'action' callback to 'before_check'.
I've also added some compatibility code, which is maybe a bit coarse but should work to keep older code working.
Reworking __getattr__ was a little annoying, but it didn't correctly handle underscores.
I'm not 100% certain this is ready to be merged, I'm just soliciting feedback at the moment.
=> "prepare" callback

tests/test_graphing.py, transitions/extensions/diagrams.py
On diagrams, change edge label to show the condition, e.g. 'heat / is_flammable'.
Conditions are separated with '&' and "unless conditions" are preceded by '!', e.g. 'heat / !is_flammable & !is_really_hot'.
=> diagrams: show conditions on edge labels

tests/test_core.py, transitions/core.py
When using the word `process` as a trigger a `RuntimeError` exception is raised due to the `process` method calling itself infinitely. Changing the name of the method to `_process` fixes that.
=> Fix 'RuntimeError: maximum recursion depth exceeded'

Changelog.md, README.md, tests/test_core.py, tests/test_nesting.py, transitions/core.py, transitions/extensions/nesting.py
Added a super call in `Machine` (#112) and added optional `allow_substates` argument for `HierarchicalStateMachine.is_state` (#113).
The super call is surrounded with try/except to prevent cryptic `object.__init__() takes no parameters` errors if wrong parameters are passed.
=> Fixes Issues #112 and #113

transitions/core.py
Fixes inability to pickle using dill by removing the nesting of Condition within Transition. At some point in future when dill handles nested classes, we should undo this change.
=> moved Condition class to module level to address #119

.gitignore, requirements_test.txt, tox.ini
This pull-request adds a tox config file that makes it easy to run tests against python2 and python3 in independent virtual environments.
Missing interpreters will be skipped.
It is even possible to run the tests in parallel using detox.
=> Added tox config file for easy multi-environment testing.

tests/test_core.py, transitions/core.py
I added a check whether a model already contains a ‘trigger’ attribute to prevent accidental overriding. 
I am a bit unsure about what a decent ‘plan B’ would be.
My initial idea: Adding ` _trigger` instead.
This would allow a model to change the behaviour of the actual trigger method:
e.g.
```python
class Model:
def trigger(self, *args, **kwargs):
if not self._trigger(*args, **kwargs):
```
This makes default transitions as mentioned by @wtgee easier.
But maybe you have a better idea of how to handle naming collisions in this case.
=> add attribute naming checks to prevent overrides of model.trigger

transitions/core.py
+ Fixed past-tense typo in the log-msgs about executed callbacks.
+ Replace Leaving-->Exiting to match Enter/Entering log-msgs.
+ Log WARN if modes already defines `trigger` method.
=> log, FIX #139: Kept only enter/exit in log-INFO

transitions/core.py
Closes #149. This just funnels `prepare` calls through `Machine._callback`, same as the other callbacks. @aleneum or @wtgee, feel free to merge, unless there's some reason I'm missing to handle `prepare` differently.
=> ensures 'prepare' is handled in the same way as other callbacks

tests/test_core.py, transitions/core.py
Addresses issue in #153--allows `State` instances to be passed in as arguments to `add_transition` instead of requiring strings.
=> allows passing State instances instead of names; closes #153

README.md, tests/test_threading.py, tests/utils.py, transitions/extensions/locking.py
Thanks for the great library!
Small addition, to allow specifying a lock instance, or an arbitrary set of managers in LockedMachine.
=> Allow injecting lock instance (or any arbitrary context manager) into LockedMachine

tests/test_add_remove.py, tests/test_graphing.py, transitions/core.py, transitions/extensions/diagrams.py, transitions/extensions/nesting.py
In the interest of having a single(ton) state machine definition apply repeatedly to temporary model instances, I've tried to adapt Machine to allow adding models after the fact. (see #165)
This works fine for the core tests, but appears to break anything nested related, so more work from me is required. If anyone with experience in the 'nested' extension can give some insight, it would be appreciated!
=> Separate add_models method for core.Machine

README.md, tests/test_add_remove.py, tests/test_threading.py, transitions/core.py, transitions/extensions/locking.py
- Allow not specifying initial state in machine.__init__ when no models are being added
- Allow specifying initial state in machine.add_model, optional when initial specified in init
- Allow specifying per-machine and per-model contexts in LockedMachine. Current default behaviour of one per-machine global RLock() maintained.
=> Add per-model handling of initial states and locks

README.md
The bullets in the README where explained the order of *some* of the callbacks were very helpful, 
but I had to read the code to be sure about the other callbacks involved.
Therefor I made the following enhancements to its contents:
- Converted into a table.
- Promoted as a new section in the contents.
- Added status enter/exit Cbs,;
- Added machine default before/after
- Add section in contents.
- Format as table.
=> doc: Improve info about callback execution order

transitions/__init__.py
In testing out #176 I realized we never actually import the version number.
=> Import the version number

tests/test_core.py, transitions/core.py
Add `__repr--()` methods so that you can debug an app from the log-messages.
The difference can be seen on the `EventData` printout:
- Before:
```
<transitions.core.EventData object at 0x00000275B50534A8>
```
- After:
```
<EventData('<State('mailed')@1707857824232>', <Transition('mailed', 'tagged')@1707857837304>)@1707857821880>
```
=> feat(core): add __repr__ on basic classes to facilitate debugging

tests/test_graphing.py, tests/test_nesting.py, tests/test_threading.py
It simply does not fail when PyGraphiviz is not installed.
This is needed on Windows because there is not yet a *wheel* for python-3.5+
=> fix(test): skip tests relying on *pygraphviz* if not installed

tests/test_add_remove.py, tests/test_core.py, transitions/core.py
I change certain e xceptiions from `MachineError` either to:
- `ValueError`, e.g. when they are thrown for contructor arg errors), 
- `AttributeErrors`, when invoking a non-existing trigger on the machine
The purpose is for a Machine clients to handle "dynamic" errors that
denote inability to process transition,
differently from "static" setup/configuration errors.
=> feat(core): raise MachineError only for internal-errors

README.md, tests/test_core.py, transitions/core.py
This adds a new notation to specify reflexive states. It is specially handy if you want to specify reflexive transitions for multiple states at once:
```
machine.add_transition('touch', ['liquid', 'gas', 'plasma'], '=', after='change_shape')
```
This would basically add three transitions from the three states using the `touch` trigger with the source state as destination state.
=> Reflexive state notation

README.md
changed some callbacks names in 'execution order' section to reflect the real names of the callbacks
=> update callbacks list in README.md

tests/test_graphing.py, transitions/extensions/diagrams.py
This isn't much, but this bug actually happened to me, so I've fixed this for posterity :)
Also, at work I use a slightly older version of your library. When I tried to generate a graph on Windows for "\*" transition (that is: source='\*'), I got an error "KeyError: 'agedge: no key'". I could not reproduce it on my Linux PC. Was this a known bug and I should just update the library or you have no knowledge on that and I should investigate further?
=> Fixed auto_transition discovery in diagrams

transitions/core.py
This can be useful for state mixins, see also Issue #229.
—as discussed.
Tested with:
```
from transitions import Machine
from transitions.extensions.states import add_state_features, Timeout
import time
@add_state_features(Timeout)
class CustomMachine(Machine):
pass
class Model(object):
def timeout(self):
print("Timeout!")
self.to_A()
model = Model()
states = ['A',
{'name': 'B', 'timeout': 0.3, 'on_timeout': 'timeout'},
{'name': 'C', 'timeout': 0.9, 'on_timeout': model.timeout}]
m = CustomMachine(model, states=states, initial='A')
model.to_B()
time.sleep(1)  # >>> "Timeout!"
print model.state  # >>>  'A'
def hello():
print("hello")
m.add_state("bob", timeout=0.5, on_timeout=hello)
model.to_bob()
time.sleep(1)
```
=> let Machine.add_states() take **kwargs

tests/test_core.py, tests/test_graphing.py, transitions/extensions/diagrams.py
Graph.rep() assumes that every callable has a `__name__` attribute.
However, callables like `functools.partial` and other classes with a
`__call__()` method have no `__name__`.  This patch modifies
`Graph.rep()` to first check whether the condition is a string and
return it, then try to return `f.__name__` (that is the current
behavior) and if that fails, then it calls `str()` on the argument.
`str()` should never fail and it is now the responsibility of the user
to return something meaningful from `__str__()`.
=> Fix graph crash with partial conditions

tests/test_core.py, transitions/core.py
When on_(enter|exit) callback is explicitly specified during state creation
_and_ corresponding model method exists _and_ its name equals default state
callback name (i.e. 'on_exit_STATENAME' or 'on_enter_STATENAME') then
callback is added twice. This patch fixes that case.
=> Fix double state callbacks.

transitions/core.py
[Note the plural]
This is consistent with `add_state` (singular) and `add_states` (plural)
and also with the ability of `__init__` to take a list of transitions.
I simply extracted the routine in `__init__` to its own method.
---
As a side note, I would prefer that `add_states` and
`add_transitions` take star-args so that the user does not need
the `[]` (easily forgotten)...
Something like:
```
...
add_states(self, *states):
for s in states:
self.add_state(s)
add_transitions(self, *transitions):
for t in transitions:
self.add_transition(t)
...
machine.add_states(STATE1, STATE2)   # That seems more natural to me.
machine.add_states(*STATES)
```
I am not holding my breath, though, because that would be a
breaking change.
=> Add Machine.add_transitions to core

transitions/extensions/states.py
This way, a program currently in a timeout state can exit immediately without having to determine if it needs to change to a non-timeout state. A simple proof of concept:
```python
#!/usr/bin/python
import sys 
import logging
from transitions import Machine
from transitions.extensions.states import add_state_features, Timeout
@add_state_features(Timeout)
class TimeoutMachine(Machine):
pass
class TestMachine(object):
states = [{'name': 'init'},
{'name': 'one', 'timeout': 5, 'on_timeout': 'to_two'},
{'name': 'two', 'timeout': 5, 'on_timeout': 'to_one'},]
def __init__(self):
self.fsm = fsm = TimeoutMachine(model=self, states=self.states, initial='init')
def main():
logging.basicConfig(stream=sys.stdout, level=logging.DEBUG)
lgr = logging.getLogger()
m = TestMachine()
m.to_one()
print "Done, …
```
=> Allow the process to exit when in a timeout state.

tests/test_core.py, transitions/core.py
Hi,
This is a new `get_transitions(trigger, source="*" dest="*")`
method on `Machine`. It returns the generator of
corresponding transitions.
My use case for it is that I declare a prototype FSM in a base
class and sometimes need to add before/after callbacks
afterwards.
Moreover, I think that since `Machine` already has a few
`add/get` pairs, a `get_transitions()` method is not surprising
in the API.
Best,
Mathias
=> Get transitions

README.md
Fixed "Reflexive transitions from multiple states" header
=> Update header typo in README.md

transitions/extensions/states.py
[Thread.is_alive()](https://docs.python.org/3/library/threading.html#threading.Thread.is_alive) is a function and the call operator `()` is missing line 106 of `transitions/extensions/states.py`.
This is obviously a bug and here is the fix!
=> Fix missing () in extensions/states

setup.py
When `setup.py` is executed, it reads `README.md` using the systems default encoding. However, `README.md` contains UTF-8 encoded characters.
If installing transitions under Python 3 on a system with a non-UTF-8 locale, like `C`, Python crashes with an `UnicodeDecodeError` because it fails to decode `README.md` as ASCII, which is the default encoding in the C locale.
To reproduce:
```
virtualenv -p /usr/bin/python3 venv
. venv/bin/activate
LANG=C LC_ALL=C pip install transitions
```
This fix decodes `README.md` explicitly as UTF-8 in a way that works on both Python 2 and 3.
=> Fix installation on Python 3 with non-UTF-8 locale

.travis.yml
Since Python 3.7 was taken out of the test matrix in 9dedc70517a7f30e51e2f5b86c5a26835a03d759, Travis has shipped support for Ubuntu 16.04 and with that support for running tests on Python 3.7.
=> Run tests on Python 3.7 on Travis

setup.py
Run tests on python 3.7 added in this PR https://github.com/pytransitions/transitions/pull/337.
=> Add python 3.7 compatibility to setup

tests/test_add_remove.py
`MachineError` not used in the test. This PR removes its class from the import statement
=> Remove unused import in test case

tests/test_core.py, transitions/core.py
Hi, it's a simple draft attempt to add support for enums (https://github.com/pytransitions/transitions/issues/334).
The main idea is to pass states to `machine` as we can do it with strings to `State` class and work with it.
I added some tests to illustrate the api
Example:
``` python
class States(enum.Enum):
RED = 1
YELLOW = 2
GREEN = 3
m = Machine(states=States, initial=States.YELLOW)
m.states
=> OrderedDict([('RED', <State('RED')@4370833592>), ('YELLOW', <State('YELLOW')@4370472240>), ('GREEN', <State('GREEN')@4371112008>)])
m.to_RED()
m.is_RED() # => True
m.state => <States.RED: 1>
m.add_transition('switch_to_yellow', self.States.RED, self.States.YELLOW)
```
But now in the code base, we have many conditions `isinstance(state, string_types, )` or `isinstance(state, State)`. For support …
=> Add support for enums

tests/test_async.py, transitions/extensions/asyncio.py
Order of callbacks is not respected due to use of `asyncio.gather`, thus, `after_state_change`/`before_state_change` may execute before/after any `after`/`before` callback.
=> Fix: callbacks order

transitions/core.py
on_exit was wrongly described
fixes pytransitions/transitions#375
=> modified typo in method doc string

tests/test_core.py, transitions/core.py
=> Don't mask away KeyError when executing a transition

tests/test_enum.py, transitions/core.py
Django3 introduced enums (TextChoices), but this enums has str behavior
see https://github.com/django/django/blob/master/django/db/models/enums.py#L77
isinstance(source, string_types) returns True
To avoid this behavior, we need to remove the check on str class.
=> Fix transitions for enums with str behavior (Django3)

README.md, tests/test_core.py, transitions/core.py, transitions/extensions/diagrams.py, transitions/extensions/markup.py, transitions/extensions/nesting.py
This adds a `model_attribute` argument to Machine which allows specifying the attribute name used in the model for tracking state.
As an added benefit, this also adds ability to attach multiple machines per model.
- Update instances of hard-coded `model.state` access/modification to dynamic model attribute access.
- Update docs and tests
Closes #372
=> Add support for dynamic model state attribute

transitions/extensions/asyncio.py
In https://github.com/pytransitions/transitions/blob/37fd5a31a7ba544701799bcde073f2193c033e0a/transitions/core.py#L1030-L1039 the `dispatch` method returns a boolean.
The AsyncMachine implementation did not return a value.
This PR ensures it does.
=> AsyncMachine.dispatch now returns a boolean as expected

.travis.yml, requirements_test.txt, tox.ini
I got tired of the tests being slow so I installed xdist.
On my machine with 8 cores it cuts down the runtime from 30 seconds to 11 seconds.
On Travis it should cut the tests runtime to ~20 seconds.
=> CI Improvements

tests/test_nesting.py
Coverage for these conditions were missing so I added them :smiley:.
=> Added coverage for duplicate states in HierarchicalMachine

tests/test_core.py
This test was also missing so I added it.
=> Test that the trigger name cannot be the same as the model attribute

tests/test_nesting.py, transitions/extensions/diagrams_pygraphviz.py, transitions/extensions/nesting.py
Fixes #404.
This needs documentation but I don't know which version this feature will released on.
I'm assuming 0.9.0. Am I correct?
=> Nested enums now translate to nested states

transitions/extensions/nesting.py
This is a bit more efficient as we don't need to create a list and can return as soon as any `v is None`.
=> Use generator instead of list comprehension

transitions/extensions/asyncio.py, transitions/extensions/nesting.py
Since we don't care about duplicates and checking for membership in set is O(1) on average while on a list it should be O(N) I've changed done to be a set instead of a list.
=> Use a set instead of a list to mark done states

transitions/extensions/nesting.py
There is a small typo in transitions/extensions/nesting.py.
Should read `refers` rather than `referes`.
=> docs: Fix simple typo, referes -> refers

tests/test_core.py, transitions/core.py
This PR adds `model_attribute` to predicate method name if model_attribute != default value (state)
It needs when we are using multiple states in the model.
Currently `transitions` generates only single method `is_{state_name}`. And if we have the same states in the model as in the test case. ['A', 'B'] for first state and ['A', 'B'] for the second state we can't use predicate methods because the instance already has this predicate for first state
Solutuon: separate predicate methods by name `is_{method_attr}_{state_name}`
=> Use model_attribute in predicate method name

tests/test_enum.py, transitions/extensions/diagrams_pygraphviz.py
The example from `README.md` for `GraphMachine` fails if machine states are enums.
=> Fix diagrams_pygraphviz.Graph.get_graph method when states are enums

transitions/extensions/nesting.py
If we set a nested state's initial value to an enum it doesn't get resolved and raises a KeyError instead.
I'm not sure which test case reproduces this directly though so I'd appriciate if you can write a unit test for this.
=> Fix resolving enums when they are set as nested initial states

pytest.ini
Pytest will now fail on any warning not explictly ignored.
This is a good idea since unawaited coroutines issue a RuntimeWarning instead of an exception. I hope that will change one day but in the meanwhile, this is a good workaround.
=> Treat warnings as errors to not miss unawaited coroutines

tests/test_core.py, transitions/core.py
If you attempt to listify an empty weak reference you get a `ReferenceError` since comparing their type to something is no longer possible.
Instead, just return a list containing the object.
=> `listify()` now supports empty weak references

setup.cfg
UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead.
Signed-off-by: Conrad Kostecki <conikost@gentoo.org>
=> setup.cfg: change description-file to description_file

README.md
If you run it with the regular `Machine` (imported from `transitions`) you'll get this error:
```
In [14]: collector = Machine(states=states, transitions=transitions, initial='waiting')
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-14-cb0d383f0648> in <module>
----> 1 collector = Machine(states=states, transitions=transitions, initial='waiting')
~/.virtualenvs/jst/lib/python3.9/site-packages/transitions/core.py in __init__(self, model, states, initial, transitions, send_event, auto_transitions, ordered_transitions, ignore_invalid_triggers, before_state_change, after_state_change, name, queued, prepare_event, finalize_event, model_attribute, on_exception, **kwargs)
577 …
```
=> Make counter example use `HierarchicalMachine` explicitly to be more clear

README.md
The main `README.md` file, section "Non-Quickstart/State", is missing an import in the example.
```
from transitions import State
```
It should be
```
from transitions import Machine, State
```
Fix for issue #541
=> Missing "Machine" import

transitions/extensions/states.py
Note: This involved a bit of in-browser coding, so please check for formatting issues and bugs.
This change introduces a Retry mix-in which lets you limit the number of times a state may be re-entered from itself. This is useful if a state represents an operation that may need to be retried a few times, but should eventually give up.
This works really well with the Timeout mix-in:
```
{ 'name': 'PingServer',
'timeout': 1, 'on_timeout': 'to_PingServer',
'retries': 3, 'on_failure': 'to_CriticalFailure',
},
```
In this example, the `PingServer` state might involve sending a `ping` packet to a server and expecting a `pong` reply, whereupon it will transition to another state. If the timeout is met, then it would re-enter the `PingServer` state, triggering a second `ping` to be sent. But on …
=> Add Retry mix-in

transitions/extensions/asyncio.py
I wanted to initialise `AsyncTimeout` state with timeout=0, so I can set timeout after initialisation before/after entering state. But trigger is not called after setting timeout > 0, entering the state and timeout has passed.
So in my project, I set on_timeout along with the timeout before entering to state and it's working.
`AsyncTimeout._on_timeout` is a list of triggers and there is a `on_timeout` setter that listifies value before setting. `AsyncTimeout.__init__` uses setter if `timeout > 0`, but it passes directly if `timeout = 0`.
=> asyncio: Fix setting AsyncTimeout._on_timeout trigger, when timeout=0

transitions/extensions/diagrams_base.py
Fixes #582
I tested this with combinations: `on_enter`, `on_enter+on_exit`, `timeout+on_timeout`, and  `on_enter+timeout+on_timeout`
```python
states = [
{
"name": "initial",
"on_enter": ["this is odd", "see?"],
"on_exit": ["this is odd", "see?"],
"timeout": 30,
"on_timeout": ["do_something", "do_something"],
}
]
```
=> Add trailing newline to graph's node labels

transitions/extensions/states.py
There are small typos in:
- transitions/extensions/states.py
Fixes:
- Should read `keyword` rather than `keywork`.
- Should read `exceeded` rather than `excheeded`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: Fix a few typos

.github/workflows/pytest.yml, README.md
Switch from coveralls to codecov since reports for Python 2.7 and Python 3.x reports weren't merged correctly. Furthermore, coveralls official gha does not seem to support other formats than lcov (which coverage for Python 2.7 cannot generate).
=> Replace coveralls with codecov

.github/workflows/pytest.yml, .gitignore, tests/test_core.py, tests/test_graphviz.py, tests/test_nesting.py, transitions/core.py, transitions/extensions/__init__.py, transitions/extensions/factory.py, transitions/extensions/locking.py, transitions/extensions/markup.py, transitions/extensions/nesting.py
Fix failing GHA, update tested Python versions and add common `.venv` to the ignored folders. 
Contributed by @ipeluffo.
=> Dev #623 testing

conftest.py, transitions/core.py, transitions/extensions/asyncio.py, transitions/extensions/diagrams.py, transitions/extensions/diagrams_base.py, transitions/extensions/diagrams_graphviz.py, transitions/extensions/diagrams_pygraphviz.py, transitions/extensions/factory.py, transitions/extensions/locking.py, transitions/extensions/markup.py, transitions/extensions/nesting.py, transitions/extensions/states.py, transitions/version.py
Closes #599
I've used [ruff](https://github.com/astral-sh/ruff) with autofix options and rule [D210](https://docs.astral.sh/ruff/rules/surrounding-whitespace/).
```
ruff check --select D210 . --fix
```
=> Remove surrounding whitespace from docstrings

Changelog.md, transitions/core.py, transitions/extensions/asyncio.py, transitions/extensions/nesting.py
`Exception` is not broad enough and does not catch `asyncio.CancelledError` or `KeyboardInterrupt`. `transitions` will exclusively catch `BaseException` from now on.
This has to major implications: First `on_exception` is not called when a task is cancelled. This will happen when an asynchronous event cancels currently running callbacks or a KeyboardInterrupt is called.  Second, when `queue=True`
`CancelledError` will not cause the queue to get cleared and render the machine unusable from thereon.
=> Catch `BaseException` instead of `Exception`

.coveragerc, .github/workflows/pytest.yml, conftest.py, noxfile.py, setup.py, tests/test_async.py, tests/test_parallel.py, transitions/extensions/asyncio.py
Add Python 3.12 and remove 3.7 from testing. This also adjusts the signature of `pytest_ignore_collect`.
=> Update test parameters

README.md
Related to #649.
Maybe I was having a hard time accepting the fact that I can't read, anyway decided to try improving the documentation. 
I moved some content to different sections and added a couple more to _hopefully_ make it easier to comprehend.
Feel free to reject the PR if it does not (🥲)
Best regards,
Juanmi
=> Updated README to _hopefully_ improve it

README.md
This closes #645. Switch to (manually triggered) pyp2spec builds. This just updates the Readme. The process created for #565 is not necessary any longer. When this is merged, I will archive [transitions-distributions](https://github.com/pytransitions/transitions-distribution) for now.
=> Update COPR package

Changelog.md, tests/test_async.py, tests/test_core.py, transitions/core.py, transitions/core.pyi, transitions/extensions/asyncio.py, transitions/extensions/nesting.py, transitions/extensions/nesting.pyi
=> Fixing #626: Exceptions were raised with  `may_<trigger>` even though on_exception is provided

conftest.py
Fix `pytest_ignore_collect` hook implementation to return `None` rather than `False` when the path ought not to be ignored.  This is necessary to enable the default pytest implementation of `pytest_ignore_collect()` to be used.  Otherwise, the default rules are never applied and e.g. `--ignore` does not work.
I've also reported https://github.com/pytest-dev/pytest/issues/12383 about the misleading documentation.
=> fix `pytest_ignore_collect` not to block default pytest code

Changelog.md, tests/test_parallel.py, transitions/extensions/nesting.py
=> Fix #647: Process all states in order in  `may_trigger`

Changelog.md, tests/test_experimental.py, transitions/core.py, transitions/experimental/decoration.py, transitions/experimental/decoration.pyi
As of now, transition will not decorate models with trigger and convenience functions if they are already defined on the model. The check is done in `Machine._checked_assignment`. Users had to override `_checked_assignment` if they _wanted_ to define model methods (e.g. for type checking) and have them overridden by transitions during runtime. This approach is an all or nothing solution. With `expect_override`, transitions now features an approach where developers can explicitly mark model methods that are intended to be overriden.
```python
from transitions import Machine
from transitions.experimental.decoration import expect_override
class Model:
@expect_override
def is_A(self) -> bool:  # will be overridden during initialisation of Machine
raise RuntimeError("Should be overridden")
def …
```
=> feature: expect_override decorator to mark model methods safe for overriding

tests/test_enum.py, transitions/extensions/nesting.py
Proposal to fix #695. See issues for details about the problems this PR solves. 
I've added a test that inherit from the current Nested Enum test, and changes the set-up to use StrEnum. Running it produces a crash when resolving the initial state, and a fail test on `get_transitions`. The following commits fix these failures. 
One more change is needed to correctly use `_add_enum_state`, I'll try to add a test to assert that the correct exception is raised when using the separator in an Enum Member name first.
=> Apply string_type checks and Enum checks in the correct order
