pytransitions/transitions

transitions/core.py
I believe this is a little bit cleaner
=> isinstance() can check against multiple types

tests/test_transitions.py, transitions/core.py
fixed #7 , and modify the test case
=> fixed #7: on_{state} can not work when state is not defined as string

tests/test_transitions.py, transitions/core.py
Added property initial to see the machine's initial state
=> added property initial

README.md
In my previous pr I missed another occurence of State A.
=> Changed a further occurence of State A into solid, and so on

transitions/core.py
=> Fixes string formatting syntax inside logger calls

transitions/diagrams.py
It looks like the code for the diagrams was merged incorrectly, with `_add_events` being a copy/paste of `_add_states`. I moved the original code for the events into the method and my graphs are generating again but original author might want to check out (@svdgraaf).
=> Diagrams Merged Incorrectly

transitions/core.py, transitions/diagrams.py, transitions/extensions.py
Small fix for identifying the first state.
=> Fixing double circle on first state

README.md
=> clarified wildcard transition behavior in README

README.md
=> fixed get_state() documentation

README.md
Helps when read for the first time if you know the verbose declaration of transition, the first time it is used.
=> Very minor text change

tests/test_threading.py, transitions/extensions.py
See #67 for detailed information.
=> this fixes #67; event.trigger is locked rather than single transitions.

tests/test_core.py, transitions/core.py
=> allow callables for callbacks

README.md, examples/Graph MIxin Demo.ipynb, transitions/extensions/__init__.py, transitions/extensions/diagrams.py, transitions/extensions/factory.py
Per #98, renames all instances of MachineGraphSupport to GraphMachine. Closes #98.
=> renamed MachineGraphSupport --> GraphMachine

tests/test_graphing.py, transitions/extensions/diagrams.py
Simple fix for missing edges in graph machine. Let me know if different approach is also desired to this problem.
=> Fix #105 issue - missing edges between nodes

transitions/core.py
… to avoid trigger confusion (related to #109 and ‘process’)
=> rename callback to _callback

Changelog.md, README.md, tests/test_core.py, tests/test_nesting.py, tests/test_threading.py, transitions/core.py, transitions/extensions/nesting.py
=> this fixes #140

transitions/extensions/locking.py
Well that's embarrassing (for me)... found this causing some unpleasant leakage.
=> Fix locked machine remove_model

tests/test_core.py, transitions/core.py
This adds the arguments present in add_transition, including:
* conditions
* unless
* before
* after
* prepare
* **kwargs
See #192.
=>  Add conditional transitions and callbacks to ordered transitions.

README.md
Fixes small typo on [ adding-features-to-states example](https://github.com/pytransitions/transitions#adding-features-to-states) 
Else when trying to execute the example you would AssertionError on
assert hero.state == 'preparing'  # Preparing for the night shift
=> state is called <preparing>, lowercase

.travis.yml, appveyor.yml, requirements_test.txt, setup.py, tox.ini
=> Migrate to pytest

README.md, tests/test_core.py, tests/utils.py, transitions/core.py
Includes tests for new functionality
=> Add the ability to convert a model's property name into a callable (as well)

Changelog.md, README.md, tests/test_async.py, tests/test_core.py, transitions/core.py, transitions/extensions/asyncio.py
introduce model queues for `AsyncMachine` and add event removal from queue in `Machine.remove_movel`.
This is based on #492.
=> Feature model queues

Changelog.md
Fix year in changelog for release 0.8.8.
Signed-off-by: Leon Anavi <leon.anavi@konsulko.com>
=> Changelog.md: Fix typo

README.md
I had to install `graphviz-dev` in order to install `pygraphviz`
=> Update README.md for transitions[diagrams] Linux

tests/test_graphviz.py, transitions/extensions/diagrams_base.py
=> Left-align last item in Graphviz label

README.md
Update Readme with some basic concepts.
=> Updated README to _hopefully_ improve it

Changelog.md, tests/test_graphviz.py, tests/test_nesting.py, tests/test_pygraphviz.py, transitions/extensions/diagrams.py, transitions/extensions/markup.pyi, transitions/extensions/nesting.py
make `GraphMachine.remove_transitions` update graphs (follow up to 
5c89a24)
let `HSM.remove_transitions` check transitions defined on nested states
this closes #600
=> Improve remove_transitions

Changelog.md, README.md, setup.cfg, tests/test_reuse.py, transitions/extensions/nesting.py, transitions/version.py
=> Fix for #610: Decorate models when HSM is passed to add_states

Changelog.md, tests/test_nesting.py, transitions/extensions/nesting.py
=> fix: enable override of already initialized FunctionWrapper
